let seunome = prompt("Digite seu nome: ")
let suaidade = prompt("Digite sua idade: ")
let curso = prompt("Digite seu curso atual: ")
let ano = prompt("Digite o ano atual: ")
document.write("O seu nome é: ", seunome)
document.write("<br>A sua idade é: ", suaidade)
document.write("<br>O seu curso é: ", curso)
document.write("<br>O ano atual é: ", ano)
let varString = "2048"
console.log(parseFloat(varString))
